// <auto-generated />
namespace ProdutosMarcas.Persistencia.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration_Inicial_Criacao_Produto_Marca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_Inicial_Criacao_Produto_Marca));
        
        string IMigrationMetadata.Id
        {
            get { return "202005172116185_Migration_Inicial_Criacao_Produto_Marca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
